roverdotcom/askbot-devel

- askbot/skins/rover_skin/templates/rover_assets/footer.html
https://roverdotcom.atlassian.net/browse/DEV-2438
> [DEV-2438] Update copyright to reflect current year

- askbot/migrations_askrover/0003_auto__add_field_askbotuser_date_joined.py
- askbot/models/askbot_user.py
This is a redo of the previously-merged DEV-2155 work.  We decided not to ship it until after the holidays, but we did want to ship DEV-2354, which was merged on top of it.  So, I removed the DEV-2155 work and re-added DEV-2354.
This request will re-add the DEV-2155 work so that it can be deployed after the holidays.
> REDO [DEV-2155] Add date_joined field to AskbotUser.

- askbot/middleware/feature_flag.py
@mwhansen cr?  This middleware is active via URLMiddleware and so doesn't need to do an explicit URL check.
> [DEV-2346] Remove URL check from AskbotFeatureFlagMiddleware.

- askbot/middleware/askbot_user.py
- askbot/models/__init__.py
@empanda please review and +1
The date_joined field was not getting set properly for new users
> [DEV-3208] Set date_joined on AskbotUser creation

- askbot/models/post.py
@empanda please review and +1
For the post in question, the type of "comment" which fails both the if and elif conditions in the modified line.  I verified that this gives the right html output for the failing post.
> [DEV-3223] TypeError: argument of type 'NoneType' is not iterable

- askbot/views/commands.py
- askbot/views/moderation.py
> [WIZ-1502] Fix request.raw_post_data which was deprecated in Django 1.6

- askbot/templates/meta/custom_javascript.html
@empanda please review and +1
The html for the become a sitter CTA was already there, but needed the javascript in authenticated.js to actually show / decide when to show.
> [DEV-3116] Add 'Become a sitter' CTA onto the nav bar

- askbot/templates/meta/html_head_stylesheets.html
https://roverdotcom.atlassian.net/browse/DEV-3661
> [DEV-3661] Use transitional css

- askbot_requirements.txt
> Freeze Coffin version to <2.0

- askbot_requirements_dev.txt
> Did the same thing in the `_dev` requirements file

- askbot_requirements.txt
Reverts roverdotcom/askbot-devel#79
> Revert "Freeze Coffin version to <2.0"

- askbot_requirements_dev.txt
Reverts roverdotcom/askbot-devel#80
> Revert "Did the same thing in the `_dev` requirements file"

- askbot_requirements.txt
- askbot_requirements_dev.txt
> Freeze Coffin dependency version

- askbot/__init__.py
> Updated the right requirements this time

- askbot/media/style/style.css
- askbot/search/state_manager.py
- askbot/templates/main_page/headline.html
https://roverdotcom.atlassian.net/browse/DEV-3791
> [DEV-3791] Improve Askbot tag SEO.

- askbot/templatetags/extra_tags.py
- askbot/views/readers.py
https://roverdotcom.atlassian.net/browse/DEV-3792
> [DEV-3792] Redirect to the question when a non-admin tries to access the a Post revision history

- askbot/media/js/utils.js
- askbot/templates/widgets/related_tags.html
- askbot/views/readers.py
https://roverdotcom.atlassian.net/browse/DEV-3793
> [DEV-3793] Show keywords as a dropdown in the sidebar

- askbot/views/readers.py
https://roverdotcom.atlassian.net/browse/DEV-3794
> [DEV-3794] Remove support tagged questions from the main page

- askbot/skins/rover_skin/templates/rover_assets/footer.html
https://roverdotcom.atlassian.net/browse/DEV-4276
> [DEV-4276] Fix premium insurance link in the footer

- askbot/forms.py
https://roverdotcom.atlassian.net/browse/DEV-3795
> [DEV-3795] Force questions to end in a question mark

- askbot/const/message_keys.py
- askbot/media/js/post.js
https://roverdotcom.atlassian.net/browse/DEV-3797
> [DEV-3797] Uplift error messaging to use keyword instead of tag

- askbot/views/users.py
https://roverdotcom.atlassian.net/browse/DEV-4421
> [DEV-4421] Send users to Rover.com user edit form instead of using askbots

- askbot/static/askbot/css/new_design.scss
- askbot/templates/meta/html_head_stylesheets.html
https://roverdotcom.atlassian.net/browse/DEV-4466
> [DEV-4466] Include new-design styles and SASS for askbot

- askbot/skins/rover_skin/templates/leaderboard.html
- askbot/templates/user_profile/user_info.html
- askbot/templates/widgets/user_card.html
> [DEV-4436] Update askbot to handle new get_active_services

- askbot/static/askbot/css/main_header.scss
- askbot/static/askbot/css/new_design.scss
- askbot/templates/base.html
- askbot/templates/meta/html_head_stylesheets.html
- askbot/templates/widgets/header.html
- askbot/templates/widgets/meta_nav.html
- askbot/templates/widgets/user_navigation.html
https://roverdotcom.atlassian.net/browse/DEV-4467
> [DEV-4467] Main header new design update

- askbot/static/askbot/css/new_design.scss
- askbot/static/askbot/css/question_list.scss
- askbot/static/askbot/css/sub_header.scss
- askbot/templates/main_page.html
- askbot/templates/main_page/headline.html
https://roverdotcom.atlassian.net/browse/DEV-4471
> [DEV-4471] Question list new design update

- askbot/models/post.py
https://roverdotcom.atlassian.net/browse/DEV-3689
> [DEV-3689] Escape content to prevent XSS attacks

- askbot/media/js/post.js
- askbot/media/style/style.css
- askbot/static/askbot/css/new_design.scss
- askbot/static/askbot/css/question_detail.scss
- askbot/static/askbot/css/question_list.scss
- askbot/static/askbot/css/shared.scss
- askbot/templates/macros.html
- askbot/templates/question.html
- askbot/templates/question/question_card.html
https://roverdotcom.atlassian.net/browse/DEV-4474
> [DEV-4474] Update question detail component to new design

- askbot/media/js/post.js
- askbot/media/style/style.css
- askbot/static/askbot/css/answers.scss
- askbot/static/askbot/css/new_design.scss
- askbot/static/askbot/css/question_detail.scss
- askbot/static/askbot/css/question_list.scss
- askbot/static/askbot/css/shared.scss
- askbot/templates/macros.html
- askbot/templates/question.html
- askbot/templates/question/answer_card.html
- askbot/templates/question/answer_tab_bar.html
- askbot/templates/question/content.html
- askbot/templates/question/new_answer_form.html
- askbot/templates/question/question_card.html
https://roverdotcom.atlassian.net/browse/DEV-4479
> [DEV-4479] Update answer list component to new design

- askbot/media/js/post.js
- askbot/media/style/style.css
- askbot/static/askbot/css/answers.scss
- askbot/static/askbot/css/main_sidebar.scss
- askbot/static/askbot/css/new_design.scss
- askbot/static/askbot/css/question_detail.scss
- askbot/static/askbot/css/question_list.scss
- askbot/static/askbot/css/shared.scss
- askbot/templates/macros.html
- askbot/templates/main_page/sidebar.html
- askbot/templates/question.html
- askbot/templates/question/answer_card.html
- askbot/templates/question/answer_tab_bar.html
- askbot/templates/question/content.html
- askbot/templates/question/new_answer_form.html
- askbot/templates/question/question_card.html
- askbot/templates/widgets/contributors.html
- askbot/templates/widgets/related_tags.html
- askbot/views/readers.py
https://roverdotcom.atlassian.net/browse/DEV-4472
> [DEV-4472] Update main page sidebar component to new design

- askbot/static/askbot/css/question_list.scss
- askbot/static/askbot/css/shared.scss
https://roverdotcom.atlassian.net/browse/DEV-4561
> [DEV-4561] Cleanup tag question list page

- askbot/media/js/post.js
- askbot/media/style/style.css
- askbot/static/askbot/css/main_sidebar.scss
- askbot/templates/question/sidebar.html
https://roverdotcom.atlassian.net/browse/DEV-4476
> [DEV-4476] Update question page sidebar component to new design

- askbot/media/style/style.css
- askbot/static/askbot/css/question_list.scss
- askbot/static/askbot/css/shared.scss
- askbot/templates/meta/bottom_scripts.html
https://roverdotcom.atlassian.net/browse/DEV-4469
> [DEV-4469] Update horizontal voting component to new design

- askbot/static/askbot/css/answers.scss
- askbot/static/askbot/css/question_detail.scss
- askbot/static/askbot/css/shared.scss
- askbot/templates/main_page/tab_bar.html
- askbot/templates/question/answer_tab_bar.html
- askbot/templates/tags/header.html
- askbot/templates/users.html
https://roverdotcom.atlassian.net/browse/DEV-4473
> [DEV-4473] Uplift sorting component to new design

- askbot/static/askbot/css/answers.scss
- askbot/static/askbot/css/question_list.scss
- askbot/static/askbot/css/shared.scss
https://roverdotcom.atlassian.net/browse/DEV-4470
> [DEV-4470] Updated the vertical voting component to the new design

- askbot/deps/django_authopenid/views.py
- askbot/deps/livesettings/views.py
- askbot/tests/widget_tests.py
- askbot/urls.py
- askbot/utils/decorators.py
- askbot/views/commands.py
- askbot/views/meta.py
- askbot/views/readers.py
- askbot/views/writers.py
https://roverdotcom.atlassian.net/browse/DEV-4757
> [DEV-4757] Removed use of mimetype argument

- askbot/admin.py
https://roverdotcom.atlassian.net/browse/DEV-4753
> [DEV-4753] Don't register askbot models in the admin

- askbot/const/__init__.py
- askbot/const/message_keys.py
- askbot/forms.py
- askbot/media/js/post.js
- askbot/media/style/style.css
- askbot/static/askbot/css/ask_question.scss
- askbot/static/askbot/css/new_design.scss
- askbot/static/askbot/css/shared.scss
- askbot/templates/widgets/ask_form.html
- askbot/templates/widgets/edit_post.html
- askbot/templates/widgets/markdown_help.html
https://roverdotcom.atlassian.net/browse/DEV-4480
> [DEV-4480] Uplift design on ask question page

- askbot/views/readers.py
https://roverdotcom.atlassian.net/browse/DEV-4732
> [DEV-4732] Always filter by the dogs tag if no other tags present

- askbot/management/commands/dev_backfill_dogs_tag.py
- askbot/views/meta.py
https://roverdotcom.atlassian.net/browse/DEV-4733
> [DEV-4733] Add management command to backfill dogs tag

- askbot/media/style/style.css
- askbot/static/askbot/css/question_detail.scss
- askbot/templates/macros.html
- askbot/templates/widgets/user_card.html
https://roverdotcom.atlassian.net/browse/DEV-4475
> [DEV-4475] Uplift user card to new design

- askbot/skins/rover_skin/templates/leaderboard.html
- askbot/static/askbot/css/leaderboard.scss
- askbot/static/askbot/css/new_design.scss
https://roverdotcom.atlassian.net/browse/DEV-4481
> [DEV-4481] Uplift leaderboard to new design

- askbot/media/style/style.css
- askbot/static/askbot/css/ask_question.scss
- askbot/templates/answer_edit.html
- askbot/templates/question_edit.html
- askbot/templates/widgets/answer_edit_tips.html
https://roverdotcom.atlassian.net/browse/DEV-4671 and https://roverdotcom.atlassian.net/browse/DEV-4670
> [DEV-4670] Uplift the question edit and answer edit pages to the new design

- askbot/static/askbot/css/shared.scss
- askbot/templates/faq_static.html
- askbot/templates/help.html
https://roverdotcom.atlassian.net/browse/DEV-4819
> [DEV-4819] Change Keyword to Tag

- askbot/static/askbot/css/shared.scss
- askbot/templates/widgets/system_messages.html
https://roverdotcom.atlassian.net/browse/DEV-4798
> [DEV-4798] Uplift alert messages at the top of the page to new design

- askbot/static/askbot/css/shared.scss
- askbot/templates/meta/bottom_scripts.html
- askbot/templates/question/share_buttons.html
https://roverdotcom.atlassian.net/browse/DEV-4477
> [DEV-4477] Uplift share button component to new design

- askbot/static/askbot/css/shared.scss
https://roverdotcom.atlassian.net/browse/DEV-4482
> [DEV-4482] Uplift tab component on user profile page

- askbot/media/js/user.js
- askbot/static/askbot/css/new_design.scss
- askbot/static/askbot/css/question_list.scss
- askbot/static/askbot/css/shared.scss
- askbot/static/askbot/css/user_profile.scss
- askbot/templates/macros.html
- askbot/templates/user_profile/user.html
- askbot/templates/user_profile/user_info.html
- askbot/templates/user_profile/user_network.html
- askbot/templates/user_profile/user_recent.html
- askbot/templates/user_profile/user_stats.html
- askbot/views/users.py
https://roverdotcom.atlassian.net/browse/DEV-4483
> [DEV-4483] Uplift user profile to new design

- askbot/models/question.py
https://roverdotcom.atlassian.net/browse/DEV-4941
> [DEV-4941] Fix unicode decode error on cached posts

- askbot/static/askbot/css/ask_question.scss
- askbot/static/askbot/css/main_header.scss
- askbot/static/askbot/css/main_sidebar.scss
- askbot/static/askbot/css/question_detail.scss
- askbot/static/askbot/css/shared.scss
- askbot/static/askbot/css/sub_header.scss
- askbot/static/askbot/css/user_profile.scss
- askbot/templates/embed/ask_by_widget.html
- askbot/templates/main_page/nothing_found.html
- askbot/templates/main_page/sidebar.html
- askbot/templates/meta/html_head_stylesheets.html
- askbot/templates/tags/header.html
- askbot/templates/user_inbox/base.html
- askbot/templates/user_profile/user_tabs.html
- askbot/templates/widgets/ask_form.html
- askbot/templates/widgets/markdown_help.html
- askbot/templates/widgets/scope_nav.html
- askbot/views/readers.py
https://roverdotcom.atlassian.net/browse/DEV-4911
> [DEV-4911] Askrover warranty work

- askbot/skins/rover_skin/templates/leaderboard.html
- askbot/templates/user_profile/user.html
- askbot/templates/widgets/user_card.html
https://roverdotcom.atlassian.net/browse/DEV-4889
> [DEV-4889] Added ref tags to rover links

- askbot/templates/widgets/ask_form.html
https://roverdotcom.atlassian.net/browse/DEV-5032
> [DEV-5032] Fix spelling error on ask question page

- askbot/static/askbot/css/question_list.scss
- askbot/static/askbot/css/shared.scss
https://roverdotcom.atlassian.net/browse/DEV-4972
> [DEV-4972] Reinstate timestamp on question summary

- askbot/templates/meta/custom_javascript.html
> [DEV-5308] Fix account-scorecard url

- askbot/templates/meta/bottom_scripts.html
- askbot/templates/meta/custom_javascript.html
@empanda won't you put your :eyes: on this :memo: and :+1: to unblock https://github.com/roverdotcom/web/pull/9791 ??
> [DEV-6412] rename files used in base.html

- askbot/templates/meta/bottom_scripts.html
- askbot/templates/meta/custom_javascript.html
Reverts roverdotcom/askbot-devel#145
> Revert "[DEV-6412] rename files used in base.html"

- askbot/templates/meta/bottom_scripts.html
- askbot/templates/meta/custom_javascript.html
Reverts roverdotcom/askbot-devel#147
> Revert "Revert "[DEV-6412] rename files used in base.html""

- askbot/templates/main_page/nothing_found.html
- askbot/templates/widgets/login_link.html
> [DEV-8251] Fix URL reverse in nothing_found.html

- askbot/models/post.py
> [DEV-8262] Missing import in post

- askbot/templates/user_profile/user_stats.html
- askbot/views/readers.py
@mwhansen please review and +1
https://roverdotcom.atlassian.net/browse/DEV-12083
> [DEV-12083] Make redirects from deleted questions permanent.

- askbot/views/writers.py
> [DEV-38741] dont flush session before posting anonymous, and ensure session key exists
